global:

receivers:
  - name: sink # default catch all receiver

{% if alertmanager_config.receivers is defined and alertmanager_config.receivers  | length > 0 %}
{% for item in alertmanager_config.receivers  %}
  - {{ item | to_nice_yaml(width=1337) | indent( width=4) | replace('@{', '{{' )| replace('}@', '}}' ) }}

{% endfor %}
{% endif %}


route:

  receiver: sink

  routes:
{% if alertmanager_config.routes  is defined and alertmanager_config.routes | length > 0 %}
{% for item in alertmanager_config.routes %}
    - {{ item | to_nice_yaml | indent( width=6,first=false)}}
{% endfor %}
{% endif %}

inhibit_rules:

{% if alertmanager_config.inhibit_rules is defined and alertmanager_config.inhibit_rules | length > 0 %}
{% for item in alertmanager_config.inhibit_rules %}
  - {{ item | to_nice_yaml | indent( width=4)}}
{% endfor %}
{% endif %}
