---
#============================================================================================================
# Caddy Role Defaults
#============================================================================================================

# Main role control variable
run_role_caddy: false

# set to true to uninstall caddy
remove_caddy: false

# User override variable - will be combined with defaults
caddy: {}
# Default Caddy configuration structure
caddy_defaults:
  email: "email@example.com"
  admin: "127.0.0.1:2019"
  metrics: true
  http_port: 80
  https_port: 443

  # ensure that there are at least 2GB of disk space for the build
  build_dir: "/tmp/caddy_build"
  caddy_version: "v2.10.0" # the git tag used to build caddy
  go_version: 1.25.0

  caddy_plugins: []
    # list of plugins to build caddy with, e.g.
    # - github.com/caddy-dns/cloudflare
