---
#============================================================================================================
# Zfs
#============================================================================================================
# flag that allows to disable the role
run_role_zfs: false
