---
#============================================================================================================
# Borg Backup Configuration
#============================================================================================================

# Main role control
run_role_borg: false

# User overrides - these will be combined with borg_defaults
borg: {}
# Default configuration structure
borg_defaults:
  version: "1.4.1" # check borg_checksums below

  # Server configuration
  server:
    enabled: false

    # where the backups will be stored
    data_directory: /var/borg_backups

    user:
      name: borg
      uid:
      group: borg
      gid:
      home: /home/borg

    repos: []
    # Example access structure:
    # - name: test
    #   public_key: "ssh-rsa AAAAB..."
    # check permission here: https://borgbackup.readthedocs.io/en/master/usage/serve.html
    #  "all" is needed to create the repo, otherwise it will fail. if the repo is created this can be updated.
    #   permissions: all | no-delete | write-only | read-only
    #
# Supported Borg versions and checksums
borg_checksums:
  "1.4.1": "b3ee1ce7454aacc0312c814e470df38132b1f6a71ae4164bea2b7d5033cb2480"
  "2.0.0b19": "82f799e830e06a964b002739cc2659bdd3015aa2585b6212f2dd6976eac7c841"
