---
#============================================================================================================
# ETNA FINANCE Role Defaults
#============================================================================================================

# Role execution control
run_role_etnafiance: false

# User configuration override (will be merged with etnafiance_defaults)
etnafiance: {}
# Default configuration structure
etnafiance_defaults:
  version: 0.10.3
  # User and group configuration
  user:
    name: etnafiance
    uid: # Let system assign UID
    group: etnafiance
    gid: # Let system assign GID

  # Installation paths
  paths:
    base_dir: /opt/etnafiance
    data_dir: /opt/etnafiance/data

  settings:
    financialSimulator: true
    rsu: true
    investmentInstruments: true

  # Service configuration
  service:
    bind_ip: 127.0.0.1
    port: 8085
    loglevel: info
    cookiesHashKey: "He4wazahwo6o...." # MUST BE EXACTLY 64 chars
    cookiesBlockKey: "He4wazahwo6o...." #  MUST BE EXACTLY 32 chars
    apiKeys:
      massive: []

# Supported etnafiance versions and checksums
etnafiance_checksums:
  "0.9.1": "535dd738f8e9560655c79071107877c0cb72415f4b423833eb04bf896e54fcc0"
  "0.9.2": "9256f4b7f9b96f9ecc07537fefa38f6b0b448168dc53bb1363f1e968c4298547"
  "0.9.3": "62ffdcf808f1e85ed8f25c8fe82026dd2257a7ed02f28f17e262e5a11e6341e1."
  "0.10.0": "326c87272b5ba639791395eb81f695e186a3fc91193dbb7cff161b1bca406182"
  "0.10.1": "c5c5169bef13b4e9088a142c56257faee4e5d00a198d28a5c06b3a087626df25"
  "0.10.2": "973c15d8da4c5467bccfa262137348d70e076e137eab87bc5959f998d6c51dbd"
  "0.10.3": "2941a6e3a88485032446c95a4cff3548f2221d3ddf9536099bbed6d19bc67b8a"


