---
#============================================================================================================
# linux-candy defaults
#============================================================================================================
linux_candy_defaults:
  # get url from: https://github.com/andresbott/linux-candy/releases
  version: 0.3.0
