---
#============================================================================================================
# node defaults
#============================================================================================================
node_defaults: {}
