---
#============================================================================================================
# PCSX2 defaults
#============================================================================================================
pcsx2_defaults:
  # get from: https://github.com/PCSX2/pcsx2
  version: v1.6.0
