---
#============================================================================================================
# vagrant defaults
#============================================================================================================
vagrant_defaults: {}
