---
#============================================================================================================
# vault defaults
#============================================================================================================
vault_defaults:
  # get url from: https://www.vaultproject.io/downloads
  version: "1.15.4"
