---
#============================================================================================================
# virtualbox defaults
#============================================================================================================
virtualbox_defaults:
  # virtualbox version to install
  pacakge: "virtualbox-7.1"
