---
#============================================================================================================
# ytdlp defaults
#============================================================================================================
ytdlp_defaults:
  # https://github.com/yt-dlp/yt-dlp/releases
  version: "2023.11.16"
