---
#============================================================================================================
# Basic Settings
#============================================================================================================
- hosts: all
  become: true
  roles:
    # ===============  Base  =============== #
    - base/enroll
    - base/linux-apt
    - base/linux-basic
    - base/zfs
    - base/nullmailer

    - base/smartd
    - base/hdparm

    # ===============  Base Services  =============== #
    - base-services/wireguard
    - base-services/tailscale
    - base-services/docker
    - base-services/samba
    - base-services/mariadb

    # ===============  Backup   =============== #
    - base-services/borg
    - base-services/borgmatic
    - base-services/goback

    # ===============  Security   =============== #
    - security/lynis
    - security/malwarescan

#============================================================================================================
# Linux Server
#============================================================================================================
- hosts:
    - linux_servers
  become: true
  roles:
    # ===============  Security   =============== #
    #    - security/fail2ban
    - security/crowdsec
    - security/firewall

    # ===============  Web Base  =============== #
    - web-base/php-fpm
    - web-base/caddy
    - web-base/authelia
    - web-base/vhosts # configure caddy proxies, php, etc.

    # ===============  Monitoring  =============== #
    - monitoring/prometheus
    - monitoring/alertmanager
    - monitoring/node_exporter
    - monitoring/grafana
    - monitoring/monit

    # ===============  Servarr  =============== #
    - servarr/transmission
    - servarr/prowlarr
    - servarr/sonarr
    - servarr/radarr
    - servarr/lidarr
    - servarr/whisparr
    - servarr/romm

    # ===============  Web  =============== #
    - webservices/radicale
    - webservices/fe26

    # docker compose based
    - webservices/mealie # https://github.com/mealie-recipes/mealie/discussions/801
    - webservices/homepage
    - webservices/immich
    - webservices/docmost

    # php based
    - webservices/mediawiki
    - webservices/phpmyadmin

    # servar related
    - servarr/jellyfin
    - servarr/stash
    - servarr/xbvr
    - servarr/kavita

    # ===============  Other services  =============== #
    - games/minecraft


#============================================================================================================
# Linux Desktop
#============================================================================================================

- hosts:
    - linux_desktop
  become: true
  roles:
    # basic desktop
    - desktop/vbox-guest
    - desktop/linux-desktop
    - desktop/linux-kde

    # developer apps
    - desktop/dev-apps/golang
    - desktop/dev-apps/kubectl
    - desktop/dev-apps/k9s
    - desktop/dev-apps/node
    - desktop/dev-apps/vagrant
    - desktop/dev-apps/vault
    - desktop/dev-apps/virtualbox

    # desktop apps
    - desktop/apps/freecad
    - desktop/apps/google-chrome
    - desktop/apps/jellyfin-player
    - desktop/apps/pcsx2
    - desktop/apps/prusa-slicer
    - desktop/apps/ytdlp
    - desktop/apps/linux-candy

#============================================================================================================
# post setup actions
# some roles will depend on previous configuration, e.g. web service users existent
#============================================================================================================

- hosts: all
  become: true
  roles:
    - role: base-services/goback
      vars:
        run_goback_profiles: true
    # at the end, as last step we write the new version
    - role: base/enroll
      vars:
        run_autobott_write_version: true
