# =========================== Desktop ===========================
run_role_linux_desktop: true
linux_desktop:
  user: "vagrant"
  git_repos:
    - repo: "https://github.com/octocat/Hello-World.git"
      dest: "src/hello-world" # relative to the user's home
  input_remapper:
    install: true
    presets:
      - device: "Logitech Advanced Corded Mouse M500s"
        name: "new preset"
        template: "input-remapper/presets/m500s.json"

run_role_linux_kde: true
linux_kde:
  add_kde_style: true
  add_kde_screenshots: true


# only for Virtualbox VMs
run_role_vbox_guest: false

# =========================== Desktop Apps ===========================
# GUI apps
run_role_gui_apps: true
gui_apps_config:
  virtualbox:
  freecad:
  google-chrome:
  jellium-desktop:
  pcsx2:
  prusa-slicer:


#============================================================================================================
# CLI utilities / developer toolchains
#============================================================================================================
run_role_cli_apps: true
cli_apps_config:
  ytdlp:
  linux-candy:
  dibs:
  todo:

# =========================== # NODE  ===========================
run_role_dev_node: true
dev_node_config:
  node:

# =========================== # GO  ===========================
run_role_dev_go: true
dev_go_config:
  golang:
  goreleaser:
  nfpm:
  golangci-lint:
  go-deps-view:

# =========================== # JAVA  ===========================
run_role_dev_java: true
dev_java_config:
  java_versions:
    - openjdk-21-jdk
    - openjdk-25-jdk
  jenv:
  maven:

# =========================== # K8S  ===========================
run_role_dev_k8s: true
dev_k8s_config:
  kubectl:
  k9s:

# =========================== # Other  ===========================
run_role_dev_generic: true
dev_generic_config:
  vagrant:
  vault:
  herdr:
  github-cli:




