# =========================== Desktop ===========================
run_role_linux_desktop: true
linux_desktop:
  user: "vagrant"

run_role_linux_kde: true
linux_kde:
  add_kde_elementary_breeze: true


# only for Virtualbox VMs
run_role_vbox_guest: false

# =========================== Desktop Apps ===========================
run_role_apps: true
apps_config:
  golang:
  kubectl:
  k9s:
  node:
  vagrant:
  vault:
  virtualbox:
  freecad:
  google-chrome:
  jellium-desktop:
  pcsx2:
  prusa-slicer:
  ytdlp:
  linux-candy:
  dibs:
  go-deps-view:
  todo:




