# =========================== Desktop ===========================
run_role_linux_desktop: true
linux_desktop:
  user: "vagrant"
  git_repos:
    - repo: "https://github.com/octocat/Hello-World.git"
      dest: "src/hello-world" # relative to the user's home

run_role_linux_kde: true
linux_kde:
  add_kde_style: true


# only for Virtualbox VMs
run_role_vbox_guest: false

# =========================== Desktop Apps ===========================
# GUI apps
run_role_gui_apps: true
gui_apps_config:
  virtualbox:
  freecad:
  google-chrome:
  jellium-desktop:
  pcsx2:
  prusa-slicer:
  input-remapper:

# CLI / developer apps
run_role_cli_apps: true
cli_apps_config:
  golang:
  kubectl:
  k9s:
  node:
  vagrant:
  vault:
  ytdlp:
  linux-candy:
  dibs:
  go-deps-view:
  todo:
  jenv:
  maven:
  herdr:
  github-cli:




