#ENC[AES256_GCM,data:5xn7My7hAsdAvGy69gkGZE5xPrAAeSOZ3An93KN2clEDJeBuwlAs1Dx5cNfFEDKpq3g1wB5LOekfovgsc0GzLhMPZotFZG74lleSYb8=,iv:9M7N+MoAlbjqhCGD1BFVbLj/4zYnPU0ivYecfw1DQGI=,tag:kL5TgHcdXtPwtVZQXMAmZg==,type:comment]
#ENC[AES256_GCM,data:uF1Tj3agpJ6BGwSUAXk0GDTWwusT9fwJhuVoDjyClQbn/VET,iv:17/pQ7laI1xIOCo/GWw3Y48tueOqWeao1kae44kpwGE=,tag:v7omUvQAMR2ky1To4euQNg==,type:comment]
secrets:
    ans_sudo_pw: ENC[AES256_GCM,data:+RCAVxVl,iv:WoSwNys2AVBtL38KL6r+hBfDjEwRJitgUGu5u54eHK0=,tag:6+zv9hXVrbogIR+pdJgrCA==,type:str]
    users:
        jsmith:
            passwd: ENC[AES256_GCM,data:kwt6,iv:AXz2FE7fU4LfltH73qzrjxLYIS/SbcG5rLgzInqKzWA=,tag:iTq+W665dlE5x54zGk+2qQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaHpUNlU5OWhWWTBPZ3dL
            V0VYN2tDN2tmalJiOUxyRTFnNmJXQVJRelVvCkw0RUQwZEhDcWhOejNrZ295dVNN
            bzVVSGFnV0ZoakVUTm5oc1pkWmhVV2sKLS0tIDhaVTRTbUM3eXMrNDRRbnhKSWJM
            NmhxbGk2Wk9hN243U1VlcUZUb0dyWTQKjxsCjHvuwFkDH4vUepKPl1h2hZquVaeI
            ygThsXA0Y9AA5zG9Wk8qixe2sktdTgiMN9cOt5cxumg6TEMgKAsVYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jv59tpdyjs99kmrykr9jeqwvsxfdu999rxdk98m2emsjue4l2e8spms3vh
    lastmodified: "2026-08-28T11:11:21Z"
    mac: ENC[AES256_GCM,data:RTAKqrNHvYpozinHgllHNK079sYY91Woi29krH1BXR+V78lqGmHgOQtW3fpcCfadEBkIcPGTzdvNXlCuz1hn7+UarT+E8R1wfAdSoLT4kKzOmm5t+ZzSFzIIlrd9zXd0qhjfns5GZPTml9qjCSNR3+beLUl/AZsooHG4F4+wJsk=,iv:v5dMfU7XHScQFN4k1R+E1R1bGDCeCwHcoAOqA7EM9mU=,tag:4aHOyrr8a94oP0GF0IaCTA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
