---
#============================================================================================================
# virtualbox Role - Main Tasks
#============================================================================================================
- name: Main virtualbox block
  tags:
    - virtualbox
    - untagged
  when:
    - run_role_virtualbox | bool
  block:
    - name: Set merged virtualbox configuration
      ansible.builtin.set_fact:
        virtualbox_config: "{{ virtualbox_defaults | combine(virtualbox, recursive=true) }}"

    - name: Remove keys from legacy /etc/apt/trusted.gpg
      ansible.builtin.file:
        path: /etc/apt/trusted.gpg
        state: absent

    - name: "apt | ensure virtualBox linux signing key present"
      ansible.builtin.copy:
        src: oracle_vbox.gpg
        dest: /usr/share/keyrings/oracle_vbox.gpg
        mode: "0644"

    - name: "apt | ensure virtualBox repo present"
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle_vbox.gpg] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
        filename: "virtualbox"
        state: present
        update_cache: yes

    - name: "apt | ensure virtualBox present"
      apt:
        name: "{{ virtualbox_config.pacakge }}"
        state: present

