---
#============================================================================================================
# virtualbox Role - Main Tasks
#============================================================================================================
- name: Main virtualbox block
  tags:
    - virtualbox
    - untagged
  when:
    - run_role_virtualbox | bool
  block:
    - name: Set merged virtualbox configuration
      ansible.builtin.set_fact:
        virtualbox_config: "{{ virtualbox_defaults | combine(virtualbox, recursive=true) }}"

    - name: Remove keys from legacy /etc/apt/trusted.gpg
      ansible.builtin.apt_key:
        id: "{{ item }}"
        state: absent
        keyring: /etc/apt/trusted.gpg
      with_items:
        - B9F8D658297AF3EFC18D5CDFA2F683C52980AECF  #oracle_vbox_2016.asc
        - 7B0FAB3A13B907435925D9C954422A4B98AB5139  #oracle_vbox.asc

    - name: "apt | ensure virtualBox linux signing key present"
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present
        keyring: /etc/apt/trusted.gpg.d/oracle_vbox.gpg

    - name: "apt | ensure virtualBox linux signing key present"
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox.asc
        state: present
        keyring: /etc/apt/trusted.gpg.d/oracle_vbox.gpg

    - name: "apt | ensure virtualBox repo present"
      apt_repository:
        repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
        filename: "virtualbox"
        state: present
        update_cache: yes

    - name: "apt | ensure virtualBox present"
      apt:
        name: "{{ virtualbox_config.pacakge }}"
        state: present

