---
#============================================================================================================
# Golang Role Defaults
#============================================================================================================

# Main role control variable
run_role_golang: false

# User override variable - will be combined with defaults
golang: {}
# Default Golang configuration structure
golang_defaults:
  # go version to install
  go_version: "1.25.5"

  # get the link from: https://github.com/niemeyer/godeb
  godeb_url: https://godeb.s3.amazonaws.com/godeb-amd64.tar.gz
  godeb_sha256: f2b3445dda98b31a32381036bf01c7e82df1a5a151e7e838ca1f0d1fb8e80952
  # get from: https://github.com/goreleaser/goreleaser/releases
  goreleaser_url: "https://github.com/goreleaser/goreleaser/releases/download/v2.18.1/goreleaser_2.18.1_amd64.deb"
  goreleaser_sha256: "f9227f77b5f7747dc3ddad211e34bacccde111a95560c5404d47add00d0aa24e"
  # get from: https://github.com/goreleaser/nfpm/releases
  nfpm_url: "https://github.com/goreleaser/nfpm/releases/download/v2.47.0/nfpm_2.47.0_amd64.deb"
  nfpm_sha256: "3f1cf344bd0b57373ca55636a78c08b0491f7293d609a456a9ac3b0b150fda97"
  # get from https://github.com/golangci/golangci-lint/releases
  golangci_lint_url: "https://github.com/golangci/golangci-lint/releases/download/v2.13.2/golangci-lint-2.13.2-linux-amd64.deb"
  golangci_lint_sha256: "7ef9114c71db2e6b8529fc58ef4575b02661f6e0a45aeb50248f2a86f8ea50a9"
