---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: Restart whisparr
  ansible.builtin.service:
    name: whisparr
    state: restarted
  listen: restart whisparr