- name: Get SSH key for {{ item }}
  command: "ssh-keyscan -H {{ item }}"
  register: sshkey_output
  changed_when: false
  failed_when: sshkey_output.rc != 0
  ignore_errors: yes

- name: Fail if SSH key for {{ item }} could not be retrieved
  fail:
    msg: >
      Failed to retrieve SSH key for host '{{ item }}'.
      This usually means the host does not resolve or is unreachable.
      ssh-keyscan stderr: {{ sshkey_output.stderr }}
  when: sshkey_output.rc != 0

- name: Add {{ item }} to known_hosts
  known_hosts:
    name: "{{ item }}"
    key: "{{ sshkey_output.stdout }}"
    path: "/root/.ssh/known_hosts"
  when: sshkey_output.rc == 0