---
#============================================================================================================
# PHP-FPM Role Defaults
#============================================================================================================

# Main role control variable
run_role_php_fpm: false

# set to true to uninstall php fpm
remove_php_fpm: false

# User override variable - will be combined with defaults
php_fpm: {}
# Default PHP-FPM configuration structure
php_fpm_defaults:


  # System configuration
  system:
    group_name: "php-worker"
    group_system: true

  # Cleanup configuration

  # PHP configuration settings
  runtime:
    # Output buffering
    output_buffering: 4096

    # Resources
    max_execution_time: 30
    max_input_time: 60
    memory_limit: "128M"
    max_input_vars: 1500

    # Error handling
    error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
    display_errors: "Off"
    display_startup_errors: "Off"
    log_errors: "On"

    # Uploads
    post_max_size: "30M"
    file_uploads: "On"
    upload_max_filesize: "30M"
    max_file_uploads: 20

    # Sessions
    session_use_strict_mode: 1
    session_name: "PHPSESSID"

    # OPcache
    opcache:
      enable: 1
      memory_consumption: 128
      interned_strings_buffer: 8
      max_accelerated_files: 10000
      max_wasted_percentage: 5
      use_cwd: 1
      validate_timestamps: 1
      revalidate_freq: 2
      revalidate_path: 0
      save_comments: 0
      enable_file_override: 0
      optimization_level: "0x7FFFBFFF"
      max_file_size: 0
      force_restart_timeout: 180
      error_log: ""
      log_verbosity_level: 1
      preferred_memory_model: ""
      consistency_checks: 1
