---
# Docker CE installation and configuration
# This role installs and configures Docker CE on Debian/Ubuntu systems

- name: Main Docker block
  tags:
    - docker
    - untagged
  when:
    - run_role_docker | bool
  block:
    - name: Set merged docker facts
      ansible.builtin.set_fact:
        docker_data: "{{ docker_defaults | combine(docker, recursive=True) }}"

    - name: Remove old Docker packages
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
          - docker-doc
          - podman-docker
          - docker-desktop
        state: absent
        purge: true
        autoremove: true

    - name: Install required dependencies
      ansible.builtin.apt:
        name:
          - curl
          - gnupg
        state: present
        update_cache: true

    - name: Create Docker GPG key directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Copy GPG key for the current distribution
      ansible.builtin.copy:
        src: "files/{{ ansible_distribution | lower }}.gpg"
        dest: /etc/apt/keyrings/docker.asc
        owner: root
        group: root
        mode: "0644"
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release
          }} stable"
        state: present
        filename: docker
        update_cache: true

    - name: Install Docker CE packages
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: true

    - name: Create Docker daemon configuration directory
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Configure Docker daemon
      ansible.builtin.template:
        src: daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: "0644"
        validate: "dockerd --config-file %s --validate"
      notify:
        - "restart docker"

    - name: Add users to Docker group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: docker
        append: true
      loop: "{{ docker_data.users }}"
      when: docker_data.users | length > 0

    - name: Verify Docker installation
      ansible.builtin.command: docker info
      register: docker_info
      failed_when: docker_info.rc != 0
      changed_when: false
