---
#============================================================================================================
# vbox_guest Role Defaults
#============================================================================================================

# Main role control variable
run_role_vbox_guest: false

