#============================================================================================================
# Minecraft
#============================================================================================================
run_role_minecraft: true
minecraft:
  overviewer:
    enabled: true