#============================================================================================================
# k3s
#============================================================================================================
run_role_k3s_base: true
run_role_k3s_server: true