#============================================================================================================
# Jellyfin
#============================================================================================================
run_role_jellyfin: true

#============================================================================================================
# Kavita
#============================================================================================================
run_role_kavita: true

#============================================================================================================
# Transmission
#============================================================================================================
run_role_transmission: true

#============================================================================================================
# Prowlarr
#============================================================================================================
run_role_prowlarr: true

#============================================================================================================
# Lidarr
#============================================================================================================
run_role_lidarr: true

#============================================================================================================
# Radarr
#============================================================================================================
run_role_radarr: true

#============================================================================================================
# Sonarr
#============================================================================================================
run_role_sonarr: true

#============================================================================================================
# Whisparr
#============================================================================================================
run_role_whisparr: true

#============================================================================================================
# Stash
#============================================================================================================
run_role_stash: true

#============================================================================================================
# Xbvr
#============================================================================================================
run_role_xbvr: true

#============================================================================================================
# Romm
#============================================================================================================
run_role_romm: true
romm:
  db_pass: "changeme"
  app_secret: "2fb2ddea9fc62ccf712c5e6b4db50641031f9df129fbca6df14a960a9d447abb"