{
 "title": "SMART status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "disk",
    "label": "Disk",
    "query": "query_result(smartmon_device_info)"
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Info",
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "content": "## About values\n* Value: current normalized value Usually it is at 100 when everything is ok. Higher values often mean that the attribute has never been updated (implies 100).\n* Threshold: \"threshold\" is the absolute health threshold and indicates the value at/below which SMART consideres the attribute a failure. Most attributes that have a zero threshold are not critical. When they decrease, it just means that you drive gets older. Other attributes have thresholds greater than 0 and are often critical.\n* Worst: the all overtime reported worst.\n* thresholds are calculated by current value/worst - threshold i.e value 100, threshold 50 = 50\n"
    }
   ]
  },
  { "title": "Disk data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Disk Status",
   "type": "table",
   "description": "Current disk status",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "max(smartmon_device_active) by (disk)",
     "legendFormat": "active"
    },
    {
     "expr": "max(smartmon_device_info) by (disk,model_family)",
     "legendFormat": "Model"
    },
    {
     "expr": "max(smartmon_device_info) by (disk,model_family,device_model,firmware_version,serial_number)",
     "legendFormat": "device info"
    },
    {
     "expr": " max(smartmon_device_smart_healthy) by (disk)",
     "legendFormat": "Disk health"
    },
    {
     "expr": " max(smartmon_temperature_celsius_raw_value) by (disk)"
    },
    {
     "expr": " max(smartmon_power_on_hours_raw_value) by (disk) OR  max(smartmon_power_on_hours_and_msec_raw_value) by (disk)",
     "legendFormat": "Hours on"
    },
    {
     "expr": " max(smartmon_power_on_hours_value) by (disk) OR  max(smartmon_power_on_hours_and_msec_value) by (disk)",
     "legendFormat": "Hours on normalized"
    },
    {
     "expr": " max(smartmon_load_cycle_count_raw_value) by (disk)",
     "legendFormat": "head load raw"
    },
    {
     "expr": " max(smartmon_load_cycle_count_value) by (disk)",
     "legendFormat": "head load normalized"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "graph",
   "description": "Current reported disk temperature",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 2 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "smartmon_temperature_celsius_raw_value",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  { "title": "Critical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Reallocated Sector Count\t",
   "type": "graph",
   "description": "Reallocated sectors invisible to the OS\t",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "smartmon_reallocated_sector_ct_raw_value",
     "legendFormat": "Raw: {{disk}}"
    },
    {
     "expr": "smartmon_reallocated_sector_ct_worst - smartmon_reallocated_sector_ct_threshold",
     "legendFormat": "threshold: {{disk}}"
    }
   ]
  },
  {
   "title": "Reallocated sectors",
   "type": "table",
   "description": "Reallocated sectors invisible to the OS\t",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "clamp_max(smartmon_reallocated_sector_ct_worst{disk=~\"$disk\"},0)",
     "legendFormat": "$disk"
    },
    {
     "expr": "max(smartmon_reallocated_sector_ct_raw_value{disk=~\"$disk\"}) ",
     "legendFormat": "Raw count"
    },
    {
     "expr": "max(smartmon_reallocated_sector_ct_value{disk=~\"$disk\"})",
     "legendFormat": "Normalized value"
    },
    {
     "expr": "max(smartmon_reallocated_sector_ct_threshold{disk=~\"$disk\"})",
     "legendFormat": "Threshold"
    },
    {
     "expr": "max(smartmon_reallocated_sector_ct_worst{disk=~\"$disk\"})",
     "legendFormat": "Worst"
    }
   ]
  },
  {
   "title": "Offline Uncorrectable",
   "type": "graph",
   "description": "Offline uncorrectable sectors",
   "gridPos": { "h": 7, "w": 8, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "smartmon_offline_uncorrectable_raw_value",
     "legendFormat": "Raw: {{disk}}"
    },
    {
     "expr": "smartmon_offline_uncorrectable_worst - smartmon_offline_uncorrectable_threshold",
     "legendFormat": "threshold: {{disk}}"
    }
   ]
  },
  {
   "title": "Offline uncorrectable",
   "type": "table",
   "description": "Offline uncorrectable sectors",
   "gridPos": { "h": 7, "w": 3, "x": 19, "y": 11 },
   "targets": [
    {
     "expr": "clamp_max(smartmon_offline_uncorrectable_raw_value{disk=~\"$disk\"},0)",
     "legendFormat": "$disk"
    },
    {
     "expr": "max(smartmon_offline_uncorrectable_raw_value{disk=~\"$disk\"}) ",
     "legendFormat": "Raw count"
    },
    {
     "expr": "max(smartmon_offline_uncorrectable_value{disk=~\"$disk\"})",
     "legendFormat": "Normalized value"
    },
    {
     "expr": "max(smartmon_offline_uncorrectable_threshold{disk=~\"$disk\"})",
     "legendFormat": "Threshold"
    },
    {
     "expr": "max(smartmon_offline_uncorrectable_worst{disk=~\"$disk\"})",
     "legendFormat": "Worst"
    }
   ]
  },
  {
   "title": "Current Pending Sector Count\t",
   "type": "graph",
   "description": "Count of \"unstable\" sectors, still visible to the OS\t",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "smartmon_current_pending_sector_raw_value",
     "legendFormat": "Raw: {{disk}}"
    },
    {
     "expr": "smartmon_current_pending_sector_worst - smartmon_current_pending_sector_threshold",
     "legendFormat": "threshold: {{disk}}"
    }
   ]
  },
  {
   "title": "Current pending sectors",
   "type": "table",
   "description": "Count of \"unstable\" sectors, still visible to the OS\t",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "clamp_max(smartmon_current_pending_sector_raw_value{disk=~\"$disk\"},0)",
     "legendFormat": "$disk"
    },
    {
     "expr": "max(smartmon_current_pending_sector_raw_value{disk=~\"$disk\"})",
     "legendFormat": "Raw count"
    },
    {
     "expr": "max(smartmon_current_pending_sector_value{disk=~\"$disk\"})",
     "legendFormat": "Normalized value"
    },
    {
     "expr": "max(smartmon_current_pending_sector_threshold{disk=~\"$disk\"})",
     "legendFormat": "Threshold"
    },
    {
     "expr": "max(smartmon_current_pending_sector_worst{disk=~\"$disk\"})",
     "legendFormat": "Worst"
    }
   ]
  },
  {
   "title": "Reported  uncorrectable sectors",
   "type": "graph",
   "description": "Reported uncorrectable sectors",
   "gridPos": { "h": 7, "w": 8, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "smartmon_reported_uncorrect_raw_value",
     "legendFormat": "Raw: {{disk}}"
    },
    {
     "expr": "smartmon_reported_uncorrect_worst - smartmon_reported_uncorrect_threshold",
     "legendFormat": "threshold: {{disk}}"
    }
   ]
  },
  {
   "title": "Reported uncorrectable",
   "type": "table",
   "description": "Reported uncorrectable sectors",
   "gridPos": { "h": 7, "w": 3, "x": 19, "y": 18 },
   "targets": [
    {
     "expr": "clamp_max(smartmon_reported_uncorrect_raw_value{disk=~\"$disk\"},0)",
     "legendFormat": "$disk"
    },
    {
     "expr": "max(smartmon_reported_uncorrect_raw_value{disk=~\"$disk\"}) ",
     "legendFormat": "Raw count"
    },
    {
     "expr": "max(smartmon_reported_uncorrect_value{disk=~\"$disk\"})",
     "legendFormat": "Normalized value"
    },
    {
     "expr": "max(smartmon_reported_uncorrect_threshold{disk=~\"$disk\"})",
     "legendFormat": "Threshold"
    },
    {
     "expr": "max(smartmon_reported_uncorrect_worst{disk=~\"$disk\"})",
     "legendFormat": "Worst"
    }
   ]
  },
  { "title": "Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Read error rate",
   "type": "graph",
   "description": "Frequency of errors while reading raw data from a disk.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "smartmon_raw_read_error_rate_raw_value",
     "legendFormat": "Raw: {{disk}}"
    },
    {
     "expr": "smartmon_raw_read_error_rate_worst - smartmon_raw_read_error_rate_threshold",
     "legendFormat": "threshold: {{disk}}"
    }
   ]
  },
  {
   "title": "Spin Retry Count\t",
   "type": "graph",
   "description": "Total count of the spin start attempts to reach the fully operational speed",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "smartmon_spin_retry_count_raw_value",
     "legendFormat": "Raw: {{disk}}"
    },
    {
     "expr": "smartmon_spin_retry_count_worst - smartmon_spin_retry_count_threshold",
     "legendFormat": "threshold: {{disk}}"
    }
   ]
  },
  {
   "title": "Load Cycle Count",
   "type": "graph",
   "description": "Number of cycles into Landing Zone position.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "smartmon_load_cycle_count_raw_value",
     "legendFormat": "Raw: {{disk}}"
    },
    {
     "expr": "smartmon_load_cycle_count_worst - smartmon_load_cycle_count_threshold",
     "legendFormat": "threshold: {{disk}}"
    },
    {
     "expr": "changes(smartmon_load_cycle_count_raw_value[1m]) *50 >0",
     "legendFormat": "changes: {{disk}}"
    }
   ]
  }
 ]
}