{
 "title": "Status Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user'}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait'}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"})",
     "legendFormat": "Cpu Temp"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "( node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes ) / node_memory_SwapTotal_bytes\n",
     "legendFormat": "SWAP Used"
    },
    {
     "expr": "( node_memory_MemTotal_bytes\n    - node_memory_MemFree_bytes \n    - ( node_memory_Cached_bytes + node_memory_Buffers_bytes)\n ) / node_memory_MemTotal_bytes ",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "( node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "RAM Cache + Buffer"
    }
   ]
  },
  {
   "title": "Network Traffic ",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[5m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs|tmpfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs|tmpfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Status",
   "type": "table",
   "description": "Current disk status",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": " max(node_disk_meta_info) by (disk,use)",
     "legendFormat": "disk use"
    },
    {
     "expr": "sum by (disk,model_family) (max_over_time(smartmon_device_info[7d]))",
     "legendFormat": "Model"
    },
    {
     "expr": "sum by (disk,model_family,device_model,firmware_version,serial_number) (max_over_time(smartmon_device_info[7d]))",
     "legendFormat": "device info"
    },
    {
     "expr": " max(smartmon_device_smart_healthy) by (disk)",
     "legendFormat": "Disk health"
    },
    {
     "expr": " max(smartmon_temperature_celsius_raw_value) by (disk)"
    },
    {
     "expr": " max(smartmon_power_on_hours_raw_value) by (disk) OR  max(smartmon_power_on_hours_and_msec_raw_value) by (disk)",
     "legendFormat": "Hours on"
    },
    {
     "expr": " max(smartmon_power_on_hours_value) by (disk) OR  max(smartmon_power_on_hours_and_msec_value) by (disk)",
     "legendFormat": "Hours on normalized"
    },
    {
     "expr": " max(smartmon_load_cycle_count_raw_value) by (disk)",
     "legendFormat": "head load raw"
    },
    {
     "expr": " max(smartmon_load_cycle_count_value) by (disk)",
     "legendFormat": "head load normalized"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "graph",
   "description": "Current reported disk temperature",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 12 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "smartmon_temperature_celsius_raw_value",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Zfs Pool Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 21 },
   "targets": [
    { "expr": "sum by(pool) (zfs_pool_health)", "legendFormat": "__auto" },
    {
     "expr": "sum by(pool) ( zfs_pool_readonly)",
     "legendFormat": "ro"
    },
    {
     "expr": "sum by(pool) (zfs_pool_fragmentation_ratio)",
     "legendFormat": "Fragmentation"
    },
    {
     "expr": "sum by(pool) (zfs_pool_deduplication_ratio)",
     "legendFormat": "Deduplication"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 21 },
   "targets": [
    {
     "expr": "max(node_filesystem_avail_bytes{device!~'rootfs|tmpfs'}) by (device,fstype,mountpoint)"
    },
    {
     "expr": "( max(node_filesystem_size_bytes{device!~'rootfs|tmpfs'}) by (device,fstype,mountpoint) ) \n- (max(node_filesystem_avail_bytes{device!~'rootfs|tmpfs'}) by (device,fstype,mountpoint) )"
    },
    {
     "expr": "max(node_filesystem_size_bytes{device!~'rootfs|tmpfs'}) by (device,fstype,mountpoint)"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs|tmpfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs|tmpfs'})"
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Systemd Services",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "max(node_systemd_unit_state) by (name,state) > 0"
    }
   ]
  },
  {
   "title": "Systemd Failed Services",
   "type": "table-old",
   "description": "Services reported with the status Failed",
   "gridPos": { "h": 13, "w": 6, "x": 11, "y": 32 },
   "targets": [
    {
     "expr": "max(node_systemd_unit_state{ state=\"failed\"}) by (name) >0"
    }
   ]
  },
  {
   "title": "Systemd Units State",
   "type": "graph",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "node_systemd_units{state=\"activating\"}",
     "legendFormat": "Activating"
    },
    {
     "expr": "node_systemd_units{state=\"active\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_systemd_units{state=\"deactivating\"}",
     "legendFormat": "Deactivating"
    },
    {
     "expr": "node_systemd_units{state=\"failed\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "node_systemd_units{state=\"inactive\"}",
     "legendFormat": "Inactive"
    }
   ]
  }
 ]
}