---
# SFTP Configuration
# This file manages SFTP chroot jail configuration

- name: Configure SFTP chroot environment
  tags:
    - "linux-basic"
    - "untagged"
  block:
    - name: Configure SFTP subsystem
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?[ \\t]*?Subsystem(\\s*)sftp"
        line: "Subsystem sftp internal-sftp"
        validate: "/usr/sbin/sshd -t -f %s"
      notify: restart sshd

    - name: Configure SFTP chroot jails
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          Match Group {{ item.group_name }}
                  ChrootDirectory {{ item.jail_dir }}/%u
                  PasswordAuthentication {{ 'yes' if item.allow_password | default(false) else 'no' }}
                  ForceCommand internal-sftp -u {{ item.umask | default('0077') }}{{ ' -d ' + item.start_dir if item.start_dir | default('') | length > 0 else '' }}
                  AllowTcpForwarding no
                  X11Forwarding no
                  PermitTunnel no
                  AllowAgentForwarding no
        validate: "/usr/sbin/sshd -t -f %s"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - sftp jail handled by group {{ item.group_name }}"
      loop: "{{ linux_basic.ssh.sftp_jails | default([]) }}"
      when: not (item.remove | default(false))
      notify: restart sshd

    - name: Remove disabled SFTP jail configurations
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        state: absent
        validate: "/usr/sbin/sshd -t -f %s"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - sftp jail handled by group {{ item.group_name }}"
      loop: "{{ linux_basic.ssh.sftp_jails | default([]) }}"
      when: item.remove | default(false)
      notify: restart sshd
