---
# SSH Security Configuration
# This file manages SSH daemon configuration and security settings

- name: Configure SSH security settings
  tags:
    - "linux-basic"
    - "untagged"
  block:
    - name: Install dynamic SSH banner script
      ansible.builtin.template:
        src: ssh_motd.sh
        dest: /etc/update-motd.d/10-custom
        owner: root
        group: root
        mode: "0755"
      notify: restart sshd

    - name: Configure SSH daemon security options
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        validate: "/usr/sbin/sshd -t -f %s"
      loop:
        - regexp: "^#?PermitEmptyPasswords"
          line: "PermitEmptyPasswords no"
        - regexp: "^#?PermitRootLogin"
          line: "PermitRootLogin no"
        - regexp: "^#?PasswordAuthentication"
          line: "PasswordAuthentication no"
        - regexp: "^#?X11Forwarding"
          line: "X11Forwarding {{ 'yes' if linux_basic.ssh.x11_forwarding | default(false) else 'no' }}"
        - regexp: "^#?Protocol"
          line: "Protocol 2"
        - regexp: "^#?UsePAM"
          line: "UsePAM yes"
        - regexp: "^#?Banner"
          line: "Banner /etc/issue.net"
      notify: restart sshd

    - name: Create group for SSH password login
      ansible.builtin.group:
        name: "{{ linux_basic.ssh.pw_auth_group_name }}"
        state: present
      when:
        - linux_basic.ssh.pw_auth_group_name is defined
        - linux_basic.ssh.pw_auth_group_name | length > 0

    - name: Configure SSH password authentication for group
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          Match Group {{ linux_basic.ssh.pw_auth_group_name }}
                  PasswordAuthentication yes
                  AuthenticationMethods password publickey
        validate: "/usr/sbin/sshd -t -f %s"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - SSH PASSWORD AUTH GROUP"
      notify: restart sshd
      when:
        - linux_basic.ssh.pw_auth_group_name is defined
        - linux_basic.ssh.pw_auth_group_name | length > 0

    - name: Delete specific files added by cloud providers
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/ssh/sshd_config.d/50-cloud-init.conf # OVH: this one sets PasswordAuthentication yes
      notify: restart sshd
