---
#============================================================================================================
# Borgmatic Backup Configuration
#============================================================================================================

# Main role control
run_role_borgmatic: false

# User overrides - these will be combined with borgmatic_defaults
borgmatic: {}
# Default configuration structure
borgmatic_defaults:
  version: 2.0.6
  base_dir: /opt/borgmatic

borgmatic_backups: []
backups_sample:
  - name: test_php
    enabled: true
    # define the archive name string, as default the backup is used
    archive_name: test_php

    # or a list of borg repositories
    destination:
      # the path can also be a ssh repo like: ssh://qwerty.repo.borgbase.com/./repo
      - path: /backup/test_php
        label: local
        # select the encryption type, common values are: repokey, keyfile for borg1
        # and repokey-blake2-aes-ocb for borg 2
        # default is none
        # check the documentation for more details
        # if you set an encryption you also must add a encryption_passphrase
        encryption: none

    # used for encrypted repos, NOTE that only one encryption_passphrase is allowed even if
    # more than one repo is configured, this is a borgmatic limitation.
    # Important! Autobott does not have a mechanism to rotate the passphrase
    encryption_passphrase: "secure"

    ## ssh private key used if the destination is ssh
    ssh_key: |
     -----BEGIN OPENSSH PRIVATE KEY-----
     b3BlbnNzaC1rZXktdjEAAAAABG5vbmUA ...
    dirs:
      - root: /vhosts/php/home_dir/public_html
    mariadb:
      - php
      - test
    retention: "minimal" # "minimal", "medium", "aggressive"
    schedule: "weekly" # daily | weekly | monthly | none
