---
#============================================================================================================
# google-chrome Role - Main Tasks
#============================================================================================================
- name: Main google-chrome block
  tags:
    - google-chrome
    - chrome
    - untagged
  when:
    - run_role_google_chrome | bool
  block:
    - name: Set merged google-chrome configuration
      ansible.builtin.set_fact:
        google_chrome_config: "{{ google_chrome_defaults | combine(google_chrome, recursive=true) }}"

    - name: Ensure required packages for apt repository over HTTPS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Remove old / legacy google-chrome key files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/trusted.gpg.d/google.gpg
        - /etc/apt/trusted.gpg.d/google.asc
        # add others if you know them

    - name: Remove legacy /etc/apt/trusted.gpg
      ansible.builtin.file:
        path: /etc/apt/trusted.gpg
        state: absent

    - name: Copy Google signing key to keyring
      ansible.builtin.copy:
        src: google-chrome.gpg
        dest: /etc/apt/keyrings/google-chrome.gpg
        mode: '0644'

    - name: Add repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] https://dl.google.com/linux/chrome/deb/ stable main"
        filename: "google-chrome"
        state: present
      register: chrome_repo

    - name: Update apt cache if repository changed
      apt:
        update_cache: yes
      when: chrome_repo.changed

    - name: Ensure google-chrome-stable is installed
      apt:
        name: google-chrome-stable
        state: present

    # ===============================================================
    # Include profile setup per item
    # ===============================================================
    - name: Setup Chrome profiles
      include_tasks: chrome_profile.yaml
      loop: "{{ google_chrome_config.extra_profiles }}"
      loop_control:
        loop_var: profile

