---
#============================================================================================================
# Crowdsec Role
#============================================================================================================

- name: Main Crowdsec installation and configuration
  tags:
    - crowdsec
    - untagged
  when: run_role_crowdsec | bool
  block:
    - name: Set merged crowdsec configuration
      ansible.builtin.set_fact:
        crowdsec_config: "{{ crowdsec_defaults | combine(crowdsec, recursive=true) }}"

    - name: Ensure Crowdsec is installed
      apt:
        name:
          - crowdsec
          - crowdsec-firewall-bouncer
        state: present
        update_cache: yes

    - name: Update CrowdSec config.yaml with correct API port
      ansible.builtin.lineinfile:
        path: /etc/crowdsec/config.yaml
        regexp: '^\s*listen_uri:\s*'
        line: "    listen_uri: 127.0.0.1:{{ crowdsec_config.local_api_port }}"
        insertafter: '^\s*server:\s*$'
      notify: restart crowdsec

    - name: Update CrowdSec local_api_credentials.yaml with correct API URL
      ansible.builtin.lineinfile:
        path: /etc/crowdsec/local_api_credentials.yaml
        regexp: '^url:\s*'
        line: "url: http://127.0.0.1:{{ crowdsec_config.local_api_port  }}"
      notify: restart crowdsec

    - name: Update firewall bouncer api_url to match new port
      ansible.builtin.lineinfile:
        path: /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
        regexp: '^api_url:\s*'
        line: "api_url: http://127.0.0.1:{{ crowdsec_config.local_api_port }}"
      notify: restart crowdsec firewall-bouncer

    - name: Create Hub Upgrade service
      ansible.builtin.template:
        src: upgrade.service
        dest: /etc/systemd/system/crowdsec-hub-upgrade.service
        owner: root
        group: root
        mode: "0644"
        validate: /bin/systemd-analyze verify %s
      notify:
        - reload systemd

    - name: Create Hub Upgrade timer
      when: crowdsec_config.automatic_hub_upgrade
      block:
        - name: Create Hub Upgrade timer
          ansible.builtin.template:
            src: upgrade.timer
            dest: /etc/systemd/system/crowdsec-hub-upgrade.timer
            owner: root
            group: root
            mode: "0644"
            validate: /bin/systemd-analyze verify %s
          when: crowdsec_config.automatic_hub_upgrade
          notify:
            - reload systemd

        - name: Enable and start crowdsec-hub-upgrade.timer
          ansible.builtin.systemd:
            name: crowdsec-hub-upgrade.timer
            enabled: yes
            state: started

    - name: Remove Hub Upgrade timer
      when: not (crowdsec_config.automatic_hub_upgrade)
      block:

        - name: Check if the crowdsec-hub-upgrade timer exists
          ansible.builtin.stat:
            path: /etc/systemd/system/crowdsec-hub-upgrade.timer
          register: hub_timer

        - name: stop CrowdSec Hub Upgrade timer
          ansible.builtin.systemd:
            name:  crowdsec-hub-upgrade.timer
            state: stopped
            enabled: no
          when: hub_timer.stat.exists

        - name: Remove the systemd timer unit file
          ansible.builtin.file:
            path: /etc/systemd/system/crowdsec-hub-upgrade.timer
            state: absent


- name: Remove Crowdsec installation and configuration
  tags:
    - crowdsec
    - untagged
  when: not run_role_crowdsec | bool
  block:
    - name: Ensure Crowdsec and related packages are absent
      apt:
        name:
          - crowdsec
          - crowdsec-firewall-bouncer
        state: absent
        purge: yes
        autoremove: yes

    - name: Check if the crowdsec-hub-upgrade timer exists
      ansible.builtin.stat:
        path: /etc/systemd/system/crowdsec-hub-upgrade.timer
      register: hub_timer

    - name: Stop and disable the crowdsec-hub-upgrade timer
      ansible.builtin.systemd:
        name: crowdsec-hub-upgrade.timer
        state: stopped
        enabled: no
      when: hub_timer.stat.exists

    - name: Check if the crowdsec-hub-upgrade service exists
      ansible.builtin.stat:
        path: /etc/systemd/system/crowdsec-hub-upgrade.service
      register: hub_service

    - name: Stop and disable the crowdsec-hub-upgrade service
      ansible.builtin.systemd:
        name: crowdsec-hub-upgrade.service
        state: stopped
        enabled: no
      when: hub_service.stat.exists

    - name: Remove the systemd timer unit file
      ansible.builtin.file:
        path: /etc/systemd/system/crowdsec-hub-upgrade.timer
        state: absent

    - name: Remove the systemd service unit file
      ansible.builtin.file:
        path: /etc/systemd/system/crowdsec-hub-upgrade.service
        state: absent

    - name: Reload systemd to apply unit file changes
      ansible.builtin.systemd:
        daemon_reload: yes

- name: Flush handlers
  meta: flush_handlers